import re
from typing import List, Dict, Tuple


def parse_pr_url(pr_url: str) -> Tuple[str, str, int]:
    pattern = r"https://github\.com/([^/]+)/([^/]+)/pull/(\d+)"
    match = re.search(pattern, pr_url.strip())
    if not match:
        raise ValueError(
            "❌ Invalid PR URL. Expected: https://github.com/owner/repo/pull/123"
        )
    return match.group(1), match.group(2), int(match.group(3)) # owner, repo, pr number


def post_review_to_pr(github_token: str, pr_url: str, comments: List[Dict], only_high_confidence: bool = True) -> Tuple[int, str]:
    try:
        from github import Github
    except ImportError:
        raise RuntimeError("PyGithub is not installed. Run: pip install PyGithub")

    owner, repo_name, pr_number = parse_pr_url(pr_url)

    try:
        g = Github(github_token)
        repo = g.get_repo(owner + "/" + repo_name)
        pr = repo.get_pull(pr_number)
    except Exception as e:
        err = str(e).lower()
        if "401" in err or "bad credentials" in err:
            raise ValueError("🔒 Invalid GitHub token. Make sure it has 'repo' scope.")
        elif "404" in err or "not found" in err:
            raise ValueError("❌ Pull Request not found. Check the URL.")
        else:
            raise ValueError("❌ GitHub API error: " + str(e))

    to_post = comments
    if only_high_confidence:
        to_post = [c for c in comments if c.get("confidence", 0) >= 50] # filter low confidence

    if not to_post:
        raise ValueError("⚠️ No comments with confidence ≥50% to post.")

    emoji_map = {"critical": "🔴", "warning": "🟡", "suggestion": "🟢"}

    # build the summary table to post as a PR comment
    lines = [
        "## 🔍 AI Code Review Agent — Automated Review",
        "",
        "Found **" + str(len(to_post)) + "** issue(s).",
        "",
        "| Severity | Category | Function | Issue | Confidence |",
        "|---|---|---|---|---|",
    ]
    for c in to_post:
        e = emoji_map.get(c.get("severity", ""), "⚪")
        lines.append(
            "| " + e + " " + c.get("severity", "").upper() +
            " | " + c.get("category", "") +
            " | `" + c.get("function", "unknown") + "`" +
            " | " + c.get("issue", "") +
            " | " + str(c.get("confidence", 0)) + "% |"
        )
    lines += [
        "",
        "---",
        "*Generated by [AI Code Review Agent](https://github.com/shanmukhareddie/AI_code_review_agent)*"
    ]

    try:
        pr.create_issue_comment("\n".join(lines))
    except Exception as e:
        raise ValueError("❌ Failed to post comment: " + str(e))

    return len(to_post), pr.html_url
